MercadoPyme/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from PaginaWeb import views
from account.views import registro



urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('listelement.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('PaginaWeb.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('account.urls')),
    path('', views.index, name='index'),
    path('registro/', registro, name="registro"),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

PaginaWeb/urls.py
from django.urls import path
from . import views



app_name = 'PaginaWeb'
urlpatterns = [
    path('', views.index, name='index'),
    #path('Producto/<slug:url_clean>',views.DetailView.as_view(), name='detail'),
    path('Producto/<slug:url_clean>', views.detail, name='detail'),
    path('cart_detail', views.carro_detail, name='cart_detail'),
    path('cart_remove/<int:pk>', views.carro_remove, name='cart_remove'),
    path('cart_size', views.carro_size, name='cart_size'),
]

account/urls.py
from django.urls import path
from . import views

app_name = 'account'
urlpatterns = [
    
    
    
    
]

listelement/urls.py
from django.urls import path

from rest_framework import routers
from .viewset import ProductoViewSet, CategoriaViewSet

route = routers.SimpleRouter()
route.register('Producto', ProductoViewSet)
route.register('Categoria', CategoriaViewSet)

 
urlpatterns = route.urls

PaginaWeb/models.py
from django.db import models

# Create your models here.

account/models.py
from django.db import models

from django.contrib.auth.models import User

# Create your models here.


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='user/avatar')

carro/models.py
from django.db import models

# Create your models here.

listelement/models.py
from django.db import models

# Create your models here.

class Categoria(models.Model):
    
    nombre_categoria = models.CharField(max_length=255)
    url_clean = models.CharField(max_length=255, null= True)
    
   
    def __str__(self):
        return self.nombre_categoria

class Producto(models.Model):
    
    
    nombre_producto = models.CharField(max_length=255)
    url_clean = models.CharField(max_length=255, null=True)
    marca= models.CharField(max_length=255, null=True)
    proveedor = models.CharField(max_length=255, null=True)
    descripcion = models.TextField(null=True)
    precio_producto = models.IntegerField(null=True)
    codigo_producto = models.IntegerField(null=True)
    stock = models.IntegerField(null=True)
    imagen = models.ImageField(upload_to="productos", null=True)
    Categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)

    def __str__(self):
        return self.nombre_producto
    


    

account/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.files.images import get_image_dimensions

from .models import UserProfile

class CustomUserCreationForm(UserCreationForm):
    
    class Meta:
        model = User
        fields = ["username", "first_name", "last_name", "email", "password1", "password2" ]



    
 

PaginaWeb/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, redirect, get_object_or_404
from django.views import generic
from carro.carro import Carro
from django.http import HttpResponseNotFound, JsonResponse
from listelement.models import Producto, Categoria
from decimal import Decimal


# Create your views here.
def index(request):

   search = request.GET.get('search')
   category_id = request.GET.get('id')

   

   if search:  
      elements = Producto.objects.filter(nombre_producto__icontains=search)
   else:
      elements = Producto.objects

   


   elements = elements.all()
   paginator = Paginator(elements, 5)
   categories = Categoria.objects.all()



   page_number = request.GET.get('page')
   elements_page = paginator.get_page(page_number)

   return render(request, 'index.html', {'elements' : elements_page})


def detail(request, url_clean):
   element = get_object_or_404(Producto, url_clean=url_clean)
  
   if request.method == 'GET' and request.GET.get('quantity'): 
      carro = Carro(request)
      carro.add(element, int(request.GET.get('quantity')))
      
      return redirect ('PaginaWeb:detail', url_clean)
   return render(request,'detail.html', {'producto':element})


#carro

def carro_detail(request):
   return render(request, 'carro/detail.html',{'carro' : Carro(request) })

def carro_remove(request, pk):
   carro = Carro(request)
   element = get_object_or_404(Producto, pk=pk)

   carro.remove(element)
   return redirect('PaginaWeb:cart_detail')

def carro_size(request):
   cart = Carro(request)
   return JsonResponse({'size' : len(cart)}) 

   

account/views.py
from django.conf import settings
from django.contrib import messages
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login

from django.contrib.auth import login as make_login
from django.core.exceptions import ObjectDoesNotExist

from .forms import CustomUserCreationForm
from .models import UserProfile

# Create your views here.


def registro(request):

    data = {

        'form': CustomUserCreationForm()

    }

    if request.method == 'POST':
        formulario = CustomUserCreationForm(data=request.POST)
        if formulario.is_valid():
            formulario.save()
            user = authenticate(username = formulario.cleaned_data["username"], password = formulario.cleaned_data["password1"])
            login(request, user)
            return redirect(to="index")
        data["form"] = formulario


    return render(request, 'registration/registro.html', data)

carro/views.py
from django.shortcuts import render

# Create your views here.

listelement/views.py
from django.shortcuts import render

# Create your views here.

PaginaWeb/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    {% load static %}
    <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}">
    <!--<link rel="stylesheet" href="{% static 'partials/style.css' %}">-->
    <link rel="stylesheet" href="{% static '/css/all.min.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>MercadyPyme</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'partials/style.css' %}" rel="stylesheet" />
    
    
    <title>MercadoPyme</title>

    {% load static %}

    
 
    
    

</head>

<body>



    {% include "partials/header.html" %}

    <br>
    <br>
    <br>
   
        {% block content %}



        {% endblock %}
    

    {% include "partials/footer.html" %}

  
</body>

</html>

PaginaWeb/templates/carro/detail.html
{% extends 'base.html' %}

{% block content %}

{% load humanize %}


<table class="table">
    <br>
    <br>
    <br>
    <thead>
        <tr>
            <th> Imagen </th>
            <th> Producto </th>
            <th> Cantidad </th>
            <th> Precio por unidad </th>
            <th> Precio total </th>
            <th> Acciones </th>
        </tr>

    </thead>
    <tbody>



        {% for c in carro %}
        {% with product=c.element %}
        <tr>


            <td><img src="{{product.imagen.url}}" width="100" height="100" alt="Imagen producto"></td>
            <td>{{ product.nombre_producto}}</td> 
            <td>{{ c.quantity}}</td>
            <td>${{ c.precio_producto | intcomma}}</td>
            <td>${{ c.total_price | intcomma}}</td>
            <td>
                <form action="{% url 'PaginaWeb:cart_remove' product.id %}" method="post">
                    <button type="submit" class="btn btn-danger"><i class="fa fa-trash"></i></button>
                    {% csrf_token %}
                </form>
            </td>
            {% endwith %}
            {% endfor%}
        </tr>

        <tr>

            <td>Total</td>
            <td colspan="3"></td>
            <td>

                <strong>${{carro.get_total_price | intcomma}}</strong>
            </td>
        </tr>



    </tbody>

   
</table>





<div id="section-cta">
    <div class="container">
        <h3>  </h3>

        <button type="button" class="btn btn-primary float-right">Pagar</button>
        <br>

    </div>
</div>

<br>
<br>
<br>


{% endblock %}

{% include 'partials/pagination.html' with page_obj=elements%}

PaginaWeb/templates/detail.html
{% extends 'base.html' %}

{% block content %}

{% load humanize %}

<section class="py-5">
  <div class="container px-4 px-lg-5 my-5">
      <div class="row gx-4 gx-lg-5 align-items-center">
          <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0 mx-auto" src="{{producto.imagen.url}}" style="width: 300px; height: 450px" alt="..." /></div>
          <div class="col-md-6">
              <div class="small mb-1">Código: {{producto.codigo_producto}}</div>
              <h1 class="display-5 fw-bolder">{{producto.nombre_producto}}</h1>
              <div class="fs-5 mb-5">
                  <span>${{producto.precio_producto | intcomma}}</span>
              </div>
              <p class="lead">{{producto.descripcion}}</p>
              <div class="d-flex">
                  <input class="form-control text-center me-3" id="inputQuantity" type="num" value="1" style="max-width: 3rem" />
                  <form class="form-inline">
                    <div class="form-group">
                      
                      <input  required type="number" name="quantity" class="form_control with=40 mr-1" placeholder="Cantidad" value="1">
                      <button class="btn btn-secondary">Agregar</button>
  
                    </div>
                  </form>
              </div>
          </div>
      </div>
  </div>
</section>

<!--
        <div>
            <div>
            

                <img src="{{producto.imagen.url}}" width="200" height="200" alt="Imagen producto">
                <h3>Producto: {{producto.nombre_producto}}</h3>
                <h3>Precio: ${{producto.precio_producto | intcomma}}</h3>
                <h3>Marca: {{producto.marca}}</h3>
                <h3>Proveedor: {{producto.proveedor}}</h3>
                <h3>Stock: {{producto.stock}}</h3>
                <h5>Categoria: {{producto.Categoria}}</h3>

                <form class="form-inline">
                  <div class="form-group">
                    
                    <input  required type="number" name="quantity" class="form_control with=40 mr-1" placeholder="Cantidad" value="1">
                    <button class="btn btn-secondary">Agregar</button>

                  </div>


                <p>Descripcion: {{ producto.descripcion}}</p>
             
            </div>

        </div>         
-->
        
        <!-- Related items section-->
        <section class="py-5 bg-light">
          <div class="container px-4 px-lg-5 mt-5">
              <h2 class="fw-bolder mb-4">Articulos relacionados</h2>
              <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                  <div class="col mb-5">
                      <div class="card h-100">
                          <!-- Product image-->
                          <img class="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg" alt="..." />
                          <!-- Product details-->
                          <div class="card-body p-4">
                              <div class="text-center">
                                  <!-- Product name-->
                                  <h5 class="fw-bolder">Fancy Product</h5>
                                  <!-- Product price-->
                                  $40.00 - $80.00
                              </div>
                          </div>
                          <!-- Product actions-->
                          <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                              <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="#">View options</a></div>
                          </div>
                      </div>
                  </div>
                  <div class="col mb-5">
                      <div class="card h-100">
                          <!-- Sale badge-->
                          <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">Sale</div>
                          <!-- Product image-->
                          <img class="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg" alt="..." />
                          <!-- Product details-->
                          <div class="card-body p-4">
                              <div class="text-center">
                                  <!-- Product name-->
                                  <h5 class="fw-bolder">Special Item</h5>
                                  <!-- Product reviews-->
                                  <div class="d-flex justify-content-center small text-warning mb-2">
                                      <div class="bi-star-fill"></div>
                                      <div class="bi-star-fill"></div>
                                      <div class="bi-star-fill"></div>
                                      <div class="bi-star-fill"></div>
                                      <div class="bi-star-fill"></div>
                                  </div>
                                  <!-- Product price-->
                                  <span class="text-muted text-decoration-line-through">$20.00</span>
                                  $18.00
                              </div>
                          </div>
                          <!-- Product actions-->
                          <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                              <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="#">Add to cart</a></div>
                          </div>
                      </div>
                  </div>
                  <div class="col mb-5">
                      <div class="card h-100">
                          <!-- Sale badge-->
                          <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">Sale</div>
                          <!-- Product image-->
                          <img class="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg" alt="..." />
                          <!-- Product details-->
                          <div class="card-body p-4">
                              <div class="text-center">
                                  <!-- Product name-->
                                  <h5 class="fw-bolder">Sale Item</h5>
                                  <!-- Product price-->
                                  <span class="text-muted text-decoration-line-through">$50.00</span>
                                  $25.00
                              </div>
                          </div>
                          <!-- Product actions-->
                          <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                              <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="#">Add to cart</a></div>
                          </div>
                      </div>
                  </div>
                  
              </div>
          </div>
      </section>


{% endblock %}

{% include 'partials/pagination.html' with page_obj=elements%}

PaginaWeb/templates/index.html
{% extends 'base.html' %}

{% block content %}

{% load humanize %}

        <!-- Buscador-->
        <form method="get" class="form-inline my-2 my-lg-0 justify-content-center">
            <input class="w-50 mr-2 form-control-sm" type="search" name="search" aria-label="Search">           
            <button class="btn btn-primary btn-sm" type="submit">Buscar</button>
        </form>
    
    <!-- Catalogo de productos -->
    <section class="py-5">
        <div class="container px-4 px-lg-5 mt-5">
            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                {% for e in elements %}
                <div class="col mb-5">
                    <div class="card h-100">
                        <!-- Product image-->
                        <img class="card-img-top mx-auto" src="{{e.imagen.url}}" style="height: 50%; width: 50%" alt="Imagen producto" alt="..." />
                        <!-- Product details-->
                        <div class="card-body p-4">
                            <div class="text-center">
                                <!-- Product name-->
                                <h5 class="fw-bolder">{{e.nombre_producto}}</h5>
                                <!-- Product price-->
                                ${{e.precio_producto | intcomma}}
                            </div>
                        </div>
                        <!-- Product actions-->
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'PaginaWeb:detail' e.url_clean %}">Ver</a></div>
                        </div>
                    </div>
                </div>
                {% endfor %}    
            </div>
        </div>
    </section>        

{% endblock %}

{% include 'partials/pagination.html' with page_obj=elements%}

PaginaWeb/templates/partials/footer.html
<div class="text-center py-3 bg-dark text-white">© MercadoPyme
  
</div>

PaginaWeb/templates/partials/header.html
{% load static %}

<header>

<!--<link rel="stylesheet" href="{% static 'style.css' %}">-->
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container px-4 px-lg-5">
      <a class="navbar-brand" href="{% url 'index' %}">
        MercadoPyme
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto mb-2 mb-lg-0 ms-lg-4">        
          <li class="nav-item active">
            <a class="nav-link" aria-current="page" href="{% url 'index' %}">Inicio </a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item"><a class="nav-link" href="#!">Hola, {{user.username}}</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Cerrar sesion</a></li>
          {% else %}
          <li class="nav-item" ><a class="nav-link" href="{% url 'login' %}">Iniciar sesion</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'registro' %}">Registrarse</a></li>
          {% endif %}
        </ul>
        
        <div class="d-flex justify-content-end">

        <!-- Carrito -->   
        <form class="form-inline my-2 my-lg-2" action="{% url 'PaginaWeb:cart_detail' %}">
          <button class="btn btn-outline-dark" type="submit">
            <i class="bi-cart-fill me-1"></i>
            Ver carrito
          </button>
        </form> 
        </div>
           <!-- <li class="nav-item"><a id="shoppingCart" href="{% url 'PaginaWeb:cart_detail' %}" class="nav-link">
              <i class="bi-cart-fill me-1"></i>
              <span class="badge bg-dark text-white ms-1 rounded-pill">0</span>
            </a></li> -->
      </div>
    </div>
  </nav>
</header>

account/templates/profile.html
{% extends "base.html" %}


{% load static %}

{% block content %}

{% if user.is_authenticated %}

<div class="card">
    <div class="card-header">
        Perfil
    </div>
    <div class="card-body">

        <div class="row">
            <div class="col-md-4 offset-md-4">

           



            </div>
        </div>



     
        <table class="table table-borderless">

            <tbody>
                <tr>
                    <th>Usuario</th>
                    <td>{{ user.username }}</td>
                </tr>
                <tr>
                    <th>Email</th>
                    <td>{{ user.email }}</td>
                </tr>
              
              
            </tbody>
        </table>
    </div>
</div>


{% else %}
<p><a href="{% url 'login' %}">Login</a></p>
{% endif %}

<script>

    document.getElementById("customFile").addEventListener("change", function () {
        filename = this.value.split("\\").pop()
        this.nextElementSibling.textContent = filename
        document.getElementById("favatar").submit()
    })

    document.getElementById("iavatar").onclick = function(){
        document.getElementById("customFile").click()
    }
</script>

{% endblock %}

account/templates/user_data.html
{% extends "base.html" %}

{% load bootstrap %}

{% block content %}

{% if user.is_authenticated %}
    <ul>
        <li><strong>Usuario:</strong> {{ user.username }}</li>
        <li><strong>Email:</strong> {{ user.email }}</li>
        <li><strong>Autenticado:</strong> {{ user.is_authenticated }}</li>
        <li><strong>Anónimo:</strong> {{ user.is_anonymous }}</li>
    </ul>
{% else %}
    <p><a href="{% url 'login' %}">Login</a></p>
{% endif %}

{% endblock %}